# Generated by Django 6.1 on 2026-08-10 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('items', '0001_initial'),
        ('receiving', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='traceabilityrecord',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traceability_records', to='receiving.grn'),
        ),
        migrations.AddField(
            model_name='traceabilityrecord',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.item'),
        ),
        migrations.AddField(
            model_name='traceabilityrecord',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.bin'),
        ),
        migrations.AddField(
            model_name='traceabilityrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traceabilityrecord',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorybalance',
            unique_together={('item', 'warehouse')},
        ),
        migrations.AlterUniqueTogether(
            name='traceabilityrecord',
            unique_together={('item', 'serial_number')},
        ),
    ]
