# Generated by Django 6.1 on 2026-08-10 19:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asn', '0001_initial'),
        ('purchase_orders', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gate_entry_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('vehicle_number', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=200)),
                ('driver_contact', models.CharField(blank=True, max_length=50)),
                ('carrier', models.CharField(blank=True, max_length=200)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('scheduled_slot', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EXPECTED', 'Expected'), ('ARRIVED', 'Arrived'), ('SAFETY_CHECK', 'In Safety Check'), ('IN_QUEUE', 'In Queue'), ('UNLOADING', 'Unloading'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ARRIVED', max_length=20)),
                ('asn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asn.asn')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase_orders.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
