"""
Purchase order status lifecycle enumeration.
"""
from enum import Enum


class PurchaseOrderStatus(str, Enum):
    DRAFT = "DRAFT"
    CREATED = "CREATED"
    RAW_MATERIAL_REQUESTED = "RAW_MATERIAL_REQUESTED"
    RFQ_SENT = "RFQ_SENT"
    QUOTATION_RECEIVED = "QUOTATION_RECEIVED"
    PENDING_FINANCE_APPROVAL = "PENDING_FINANCE_APPROVAL"
    FINANCE_REJECTED = "FINANCE_REJECTED"
    APPROVED = "APPROVED"
    ISSUED = "ISSUED"
    ORDER_CONFIRMED = "ORDER_CONFIRMED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    ASN_SUBMITTED = "ASN_SUBMITTED"
    IN_TRANSIT = "IN_TRANSIT"
    PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED"
    FULLY_RECEIVED = "FULLY_RECEIVED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"
