"""
Repository ports for procurement module.
Defines abstract Protocol methods for saving and fetching aggregates.
"""
from __future__ import annotations

from typing import List, Optional, Protocol

from app.modules.procurement.domain.asn import ASN
from app.modules.procurement.domain.purchase_order import PurchaseOrder
from app.modules.procurement.domain.quotation import Quotation
from app.modules.procurement.domain.rfq import RFQ
from app.modules.procurement.domain.supplier import Supplier
from app.modules.procurement.domain.value_objects import (
    AsnId,
    PurchaseOrderId,
    QuotationId,
    RfqId,
    SupplierId,
)


class SupplierRepository(Protocol):
    async def find_by_id(self, supplier_id: SupplierId) -> Optional[Supplier]: ...

    async def list_all(self) -> List[Supplier]: ...

    async def save(self, supplier: Supplier) -> None:
        """Persists the Supplier aggregate."""
        ...


class RfqRepository(Protocol):
    async def save(self, rfq: RFQ) -> None: ...
    async def get_by_id(self, rfq_id: RfqId) -> Optional[RFQ]: ...
    async def list_all(self) -> List[RFQ]: ...
    async def get_next_sequence(self, year: int) -> int: ...


class QuotationRepository(Protocol):
    async def save(self, quotation: Quotation) -> None: ...
    async def get_by_id(self, quotation_id: QuotationId) -> Optional[Quotation]: ...
    async def list_all(self) -> List[Quotation]: ...


class PurchaseOrderRepository(Protocol):
    async def save(self, po: PurchaseOrder) -> None: ...
    async def get_by_id(self, po_id: PurchaseOrderId) -> Optional[PurchaseOrder]: ...
    async def get_by_number(self, po_number: str) -> Optional[PurchaseOrder]: ...
    async def list_all(self) -> List[PurchaseOrder]: ...
    async def get_next_sequence(self, year: int) -> int: ...


class AsnRepository(Protocol):
    async def save(self, asn: ASN) -> None: ...
    async def get_by_id(self, asn_id: AsnId) -> Optional[ASN]: ...
    async def list_all(self) -> List[ASN]: ...
    async def get_next_sequence(self, year: int) -> int: ...

