"""
PDF / Print export generator for Gate Entry Passes.
Renders printable HTML document with CSS styling for gate passes.
"""
from app.modules.gate.domain.aggregate import GateEntry


class GatePassPdfGenerator:
    @staticmethod
    def generate_html(entry: GateEntry) -> str:
        """Renders an HTML template formatted for downloading or printing as a gate pass."""

        # Extract details for the pass
        ocr = entry.ocr_result
        po_number = entry.po_number or "N/A"
        vehicle_plate = entry.vehicle_plate or "N/A"
        supplier_name = (ocr.supplier_name if ocr else None) or "N/A"
        material = (ocr.material_description if ocr else None) or "N/A"
        quantity = f"{ocr.total_quantity:,.2f}" if ocr and ocr.total_quantity else "N/A"

        created_at_str = entry.created_at.strftime("%d-%m-%Y %H:%M:%S") if entry.created_at else "N/A"

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Gate Pass {entry.gate_entry_number}</title>
    <style>
        body {{
            font-family: 'Courier New', Courier, monospace;
            margin: 20px;
            color: #000;
            background: #fff;
            font-size: 12px;
            max-width: 400px;
            border: 1px dashed #ccc;
            padding: 20px;
        }}
        .header {{
            text-align: center;
            border-bottom: 1px solid #000;
            padding-bottom: 10px;
            margin-bottom: 15px;
        }}
        .title {{
            font-size: 18px;
            font-weight: bold;
            margin: 0;
            text-transform: uppercase;
        }}
        .subtitle {{
            font-size: 10px;
            margin-top: 4px;
        }}
        .pass-number {{
            font-size: 14px;
            font-weight: bold;
            margin: 10px 0;
            text-align: center;
        }}
        .section-title {{
            font-size: 12px;
            font-weight: bold;
            border-bottom: 1px solid #eee;
            margin-top: 15px;
            margin-bottom: 8px;
            text-transform: uppercase;
        }}
        .field-row {{
            display: flex;
            justify-content: space-between;
            margin-bottom: 4px;
        }}
        .field-label {{
            font-weight: normal;
            color: #333;
        }}
        .field-val {{
            font-weight: bold;
            text-align: right;
        }}
        .footer {{
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #000;
            text-align: center;
            font-size: 10px;
        }}
        .signature-box {{
            margin-top: 40px;
            display: flex;
            justify-content: space-between;
        }}
        .signature-line {{
            border-top: 1px solid #000;
            width: 45%;
            padding-top: 5px;
            font-size: 9px;
            text-align: center;
        }}
        @media print {{
            body {{ border: none; margin: 0; padding: 10px; }}
            .no-print {{ display: none; }}
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1 class="title">GATE ENTRY PASS</h1>
        <div class="subtitle">WMS Logistics Management System</div>
    </div>

    <div class="pass-number">
        {entry.gate_entry_number}
    </div>

    <div class="section-title">Vehicle & Driver</div>
    <div class="field-row">
        <span class="field-label">Vehicle Plate:</span>
        <span class="field-val">{vehicle_plate}</span>
    </div>
    <div class="field-row">
        <span class="field-label">Entry Date/Time:</span>
        <span class="field-val">{created_at_str}</span>
    </div>

    <div class="section-title">Shipment Details</div>
    <div class="field-row">
        <span class="field-label">PO Number:</span>
        <span class="field-val">{po_number}</span>
    </div>
    <div class="field-row">
        <span class="field-label">Supplier:</span>
        <span class="field-val">{supplier_name}</span>
    </div>
    <div class="field-row">
        <span class="field-label">Material:</span>
        <span class="field-val">{material}</span>
    </div>
    <div class="field-row">
        <span class="field-label">Total Qty:</span>
        <span class="field-val">{quantity}</span>
    </div>

    <div class="section-title">Status</div>
    <div class="field-row">
        <span class="field-label">Entry Status:</span>
        <span class="field-val">{(entry.status.value if hasattr(entry.status, "value") else str(entry.status)).replace("_", " ").title()}</span>
    </div>
    <div class="field-row">
        <span class="field-label">Generated By:</span>
        <span class="field-val">{entry.created_by}</span>
    </div>

    <div class="signature-box">
        <div class="signature-line">Driver Signature</div>
        <div class="signature-line">Security Officer</div>
    </div>

    <div class="footer">
        Valid for one-time entry only.
        <br>Keep this pass until exit from premises.
    </div>

    <div class="no-print" style="margin-top: 20px; text-align: center;">
        <button onclick="window.print()" style="padding: 8px 16px; cursor: pointer;">Print Pass</button>
    </div>
</body>
</html>
"""
        return html

    def generate_pdf(self, entry: GateEntry) -> bytes:
        """Returns the pass HTML encoded as bytes."""
        return self.generate_html(entry).encode("utf-8")
