# Generated by Django 6.1 on 2026-08-11 03:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_type', models.CharField(choices=[('PO', 'Purchase Order'), ('INVOICE', 'Invoice'), ('PACKING_LIST', 'Packing List'), ('GRN', 'Goods Receipt Note'), ('QUALITY_CERT', 'Quality Certificate'), ('OTHER', 'Other')], max_length=50)),
                ('document_number', models.CharField(max_length=100)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('linked_entity_type', models.CharField(blank=True, max_length=50)),
                ('linked_entity_id', models.UUIDField(blank=True, null=True)),
                ('ocr_status', models.CharField(default='PENDING', max_length=20)),
                ('ocr_result', models.JSONField(blank=True, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
