/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptArrivalRouteImport } from './routes/accept-arrival'
import { Route as ArrivalSuccessRouteImport } from './routes/arrival-success'
import { Route as AssemblyDashboardRouteImport } from './routes/assembly-dashboard'
import { Route as AssemblyFinishedGoodsRouteImport } from './routes/assembly-finished-goods'
import { Route as AssemblyMaterialConsumptionRouteImport } from './routes/assembly-material-consumption'
import { Route as AssemblyMaterialIssuesRouteImport } from './routes/assembly-material-issues'
import { Route as AssemblyMaterialRequestsRouteImport } from './routes/assembly-material-requests'
import { Route as AssemblyMaterialRequirementsRouteImport } from './routes/assembly-material-requirements'
import { Route as AssemblyMaterialReservationsRouteImport } from './routes/assembly-material-reservations'
import { Route as AssemblyOrdersRouteImport } from './routes/assembly-orders'
import { Route as AssemblyProgressRouteImport } from './routes/assembly-progress'
import { Route as AssemblyQualityInspectionRouteImport } from './routes/assembly-quality-inspection'
import { Route as AssemblyReportsRouteImport } from './routes/assembly-reports'
import { Route as AssemblyReworkRouteImport } from './routes/assembly-rework'
import { Route as AssemblyScrapWastageRouteImport } from './routes/assembly-scrap-wastage'
import { Route as AssemblyWorkOrdersRouteImport } from './routes/assembly-work-orders'
import { Route as AssemblyWorkforceRouteImport } from './routes/assembly-workforce'
import { Route as DamageClaimsRouteImport } from './routes/damage-claims'
import { Route as DockAssignmentRouteImport } from './routes/dock-assignment'
import { Route as DockManagementRouteImport } from './routes/dock-management'
import { Route as DockMasterRouteImport } from './routes/dock-master'
import { Route as DriverVerificationRouteImport } from './routes/driver-verification'
import { Route as FinanceDashboardRouteImport } from './routes/finance-dashboard'
import { Route as GateDashboardRouteImport } from './routes/gate-dashboard'
import { Route as GateEntryRouteImport } from './routes/gate-entry'
import { Route as GrnRouteImport } from './routes/grn'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasterDataRouteImport } from './routes/master-data'
import { Route as MaterialDataRouteImport } from './routes/material-data'
import { Route as NewSupplierRouteImport } from './routes/new-supplier'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PickTasksRouteImport } from './routes/pick-tasks'
import { Route as ProcurementDashboardRouteImport } from './routes/procurement-dashboard'
import { Route as PurchaseOrderRouteImport } from './routes/purchase-order'
import { Route as PutawayTasksRouteImport } from './routes/putaway-tasks'
import { Route as ReceivingRouteImport } from './routes/receiving'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubmitQuotationRouteImport } from './routes/submit-quotation'
import { Route as SupplierDashboardRouteImport } from './routes/supplier-dashboard'
import { Route as UnscheduledArrivalsRouteImport } from './routes/unscheduled-arrivals'
import { Route as VehicleExitRouteImport } from './routes/vehicle-exit'
import { Route as VehicleQueueRouteImport } from './routes/vehicle-queue'
import { Route as VehicleVerificationRouteImport } from './routes/vehicle-verification'
import { Route as WarehouseDashboardRouteImport } from './routes/warehouse-dashboard'
import { Route as WarehouseStorageRouteImport } from './routes/warehouse-storage'
import { Route as FinanceApprovalsRouteImport } from './routes/finance.approvals'
import { Route as ProcurementAsnsRouteImport } from './routes/procurement.asns'
import { Route as ProcurementMaterialRequestsRouteImport } from './routes/procurement.material-requests'
import { Route as ProcurementNewRfqRouteImport } from './routes/procurement.new-rfq'
import { Route as ProcurementPurchaseOrdersRouteImport } from './routes/procurement.purchase-orders'
import { Route as ProcurementQualityIssuesRouteImport } from './routes/procurement.quality-issues'
import { Route as ProcurementQuotationsRouteImport } from './routes/procurement.quotations'
import { Route as ProcurementRfqsRouteImport } from './routes/procurement.rfqs'
import { Route as SupplierSupplierIdRouteImport } from './routes/supplier.$supplierId'
import { Route as SupplierQualityIssuesRouteImport } from './routes/supplier.quality-issues'
import { Route as WarehouseMaterialRequestsRouteImport } from './routes/warehouse.material-requests'
import { Route as WarehouseMaterialsRouteImport } from './routes/warehouse.materials'
import { Route as FinanceApprovalsIndexRouteImport } from './routes/finance.approvals.index'
import { Route as FinanceApprovalsApprovalIdRouteImport } from './routes/finance.approvals.$approvalId'
import { Route as ProcurementAsnsIndexRouteImport } from './routes/procurement.asns.index'
import { Route as ProcurementAsnsAsnIdRouteImport } from './routes/procurement.asns.$asnId'
import { Route as SupplierAsnsNewRouteImport } from './routes/supplier.asns.new'
import { Route as FinanceApprovalsCompareRfqIdRouteImport } from './routes/finance.approvals.compare.$rfqId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptArrivalRoute = AcceptArrivalRouteImport.update({
  id: '/accept-arrival',
  path: '/accept-arrival',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrivalSuccessRoute = ArrivalSuccessRouteImport.update({
  id: '/arrival-success',
  path: '/arrival-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyDashboardRoute = AssemblyDashboardRouteImport.update({
  id: '/assembly-dashboard',
  path: '/assembly-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyFinishedGoodsRoute = AssemblyFinishedGoodsRouteImport.update({
  id: '/assembly-finished-goods',
  path: '/assembly-finished-goods',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyMaterialConsumptionRoute =
  AssemblyMaterialConsumptionRouteImport.update({
    id: '/assembly-material-consumption',
    path: '/assembly-material-consumption',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssemblyMaterialIssuesRoute = AssemblyMaterialIssuesRouteImport.update({
  id: '/assembly-material-issues',
  path: '/assembly-material-issues',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyMaterialRequestsRoute =
  AssemblyMaterialRequestsRouteImport.update({
    id: '/assembly-material-requests',
    path: '/assembly-material-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssemblyMaterialRequirementsRoute =
  AssemblyMaterialRequirementsRouteImport.update({
    id: '/assembly-material-requirements',
    path: '/assembly-material-requirements',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssemblyMaterialReservationsRoute =
  AssemblyMaterialReservationsRouteImport.update({
    id: '/assembly-material-reservations',
    path: '/assembly-material-reservations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssemblyOrdersRoute = AssemblyOrdersRouteImport.update({
  id: '/assembly-orders',
  path: '/assembly-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyProgressRoute = AssemblyProgressRouteImport.update({
  id: '/assembly-progress',
  path: '/assembly-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyQualityInspectionRoute =
  AssemblyQualityInspectionRouteImport.update({
    id: '/assembly-quality-inspection',
    path: '/assembly-quality-inspection',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssemblyReportsRoute = AssemblyReportsRouteImport.update({
  id: '/assembly-reports',
  path: '/assembly-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyReworkRoute = AssemblyReworkRouteImport.update({
  id: '/assembly-rework',
  path: '/assembly-rework',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyScrapWastageRoute = AssemblyScrapWastageRouteImport.update({
  id: '/assembly-scrap-wastage',
  path: '/assembly-scrap-wastage',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyWorkOrdersRoute = AssemblyWorkOrdersRouteImport.update({
  id: '/assembly-work-orders',
  path: '/assembly-work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AssemblyWorkforceRoute = AssemblyWorkforceRouteImport.update({
  id: '/assembly-workforce',
  path: '/assembly-workforce',
  getParentRoute: () => rootRouteImport,
} as any)
const DamageClaimsRoute = DamageClaimsRouteImport.update({
  id: '/damage-claims',
  path: '/damage-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const DockAssignmentRoute = DockAssignmentRouteImport.update({
  id: '/dock-assignment',
  path: '/dock-assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const DockManagementRoute = DockManagementRouteImport.update({
  id: '/dock-management',
  path: '/dock-management',
  getParentRoute: () => rootRouteImport,
} as any)
const DockMasterRoute = DockMasterRouteImport.update({
  id: '/dock-master',
  path: '/dock-master',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverVerificationRoute = DriverVerificationRouteImport.update({
  id: '/driver-verification',
  path: '/driver-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceDashboardRoute = FinanceDashboardRouteImport.update({
  id: '/finance-dashboard',
  path: '/finance-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GateDashboardRoute = GateDashboardRouteImport.update({
  id: '/gate-dashboard',
  path: '/gate-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GateEntryRoute = GateEntryRouteImport.update({
  id: '/gate-entry',
  path: '/gate-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const GrnRoute = GrnRouteImport.update({
  id: '/grn',
  path: '/grn',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataRoute = MasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialDataRoute = MaterialDataRouteImport.update({
  id: '/material-data',
  path: '/material-data',
  getParentRoute: () => rootRouteImport,
} as any)
const NewSupplierRoute = NewSupplierRouteImport.update({
  id: '/new-supplier',
  path: '/new-supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PickTasksRoute = PickTasksRouteImport.update({
  id: '/pick-tasks',
  path: '/pick-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementDashboardRoute = ProcurementDashboardRouteImport.update({
  id: '/procurement-dashboard',
  path: '/procurement-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrderRoute = PurchaseOrderRouteImport.update({
  id: '/purchase-order',
  path: '/purchase-order',
  getParentRoute: () => rootRouteImport,
} as any)
const PutawayTasksRoute = PutawayTasksRouteImport.update({
  id: '/putaway-tasks',
  path: '/putaway-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivingRoute = ReceivingRouteImport.update({
  id: '/receiving',
  path: '/receiving',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitQuotationRoute = SubmitQuotationRouteImport.update({
  id: '/submit-quotation',
  path: '/submit-quotation',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierDashboardRoute = SupplierDashboardRouteImport.update({
  id: '/supplier-dashboard',
  path: '/supplier-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UnscheduledArrivalsRoute = UnscheduledArrivalsRouteImport.update({
  id: '/unscheduled-arrivals',
  path: '/unscheduled-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleExitRoute = VehicleExitRouteImport.update({
  id: '/vehicle-exit',
  path: '/vehicle-exit',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleQueueRoute = VehicleQueueRouteImport.update({
  id: '/vehicle-queue',
  path: '/vehicle-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleVerificationRoute = VehicleVerificationRouteImport.update({
  id: '/vehicle-verification',
  path: '/vehicle-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseDashboardRoute = WarehouseDashboardRouteImport.update({
  id: '/warehouse-dashboard',
  path: '/warehouse-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseStorageRoute = WarehouseStorageRouteImport.update({
  id: '/warehouse-storage',
  path: '/warehouse-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceApprovalsRoute = FinanceApprovalsRouteImport.update({
  id: '/finance/approvals',
  path: '/finance/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementAsnsRoute = ProcurementAsnsRouteImport.update({
  id: '/procurement/asns',
  path: '/procurement/asns',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementMaterialRequestsRoute =
  ProcurementMaterialRequestsRouteImport.update({
    id: '/procurement/material-requests',
    path: '/procurement/material-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProcurementNewRfqRoute = ProcurementNewRfqRouteImport.update({
  id: '/procurement/new-rfq',
  path: '/procurement/new-rfq',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementPurchaseOrdersRoute =
  ProcurementPurchaseOrdersRouteImport.update({
    id: '/procurement/purchase-orders',
    path: '/procurement/purchase-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProcurementQualityIssuesRoute =
  ProcurementQualityIssuesRouteImport.update({
    id: '/procurement/quality-issues',
    path: '/procurement/quality-issues',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProcurementQuotationsRoute = ProcurementQuotationsRouteImport.update({
  id: '/procurement/quotations',
  path: '/procurement/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRfqsRoute = ProcurementRfqsRouteImport.update({
  id: '/procurement/rfqs',
  path: '/procurement/rfqs',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierSupplierIdRoute = SupplierSupplierIdRouteImport.update({
  id: '/supplier/$supplierId',
  path: '/supplier/$supplierId',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierQualityIssuesRoute = SupplierQualityIssuesRouteImport.update({
  id: '/supplier/quality-issues',
  path: '/supplier/quality-issues',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseMaterialRequestsRoute =
  WarehouseMaterialRequestsRouteImport.update({
    id: '/warehouse/material-requests',
    path: '/warehouse/material-requests',
    getParentRoute: () => rootRouteImport,
  } as any)
const WarehouseMaterialsRoute = WarehouseMaterialsRouteImport.update({
  id: '/warehouse/materials',
  path: '/warehouse/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceApprovalsIndexRoute = FinanceApprovalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceApprovalsRoute,
} as any)
const FinanceApprovalsApprovalIdRoute =
  FinanceApprovalsApprovalIdRouteImport.update({
    id: '/$approvalId',
    path: '/$approvalId',
    getParentRoute: () => FinanceApprovalsRoute,
  } as any)
const ProcurementAsnsIndexRoute = ProcurementAsnsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProcurementAsnsRoute,
} as any)
const ProcurementAsnsAsnIdRoute = ProcurementAsnsAsnIdRouteImport.update({
  id: '/$asnId',
  path: '/$asnId',
  getParentRoute: () => ProcurementAsnsRoute,
} as any)
const SupplierAsnsNewRoute = SupplierAsnsNewRouteImport.update({
  id: '/supplier/asns/new',
  path: '/supplier/asns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceApprovalsCompareRfqIdRoute =
  FinanceApprovalsCompareRfqIdRouteImport.update({
    id: '/compare/$rfqId',
    path: '/compare/$rfqId',
    getParentRoute: () => FinanceApprovalsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-arrival': typeof AcceptArrivalRoute
  '/arrival-success': typeof ArrivalSuccessRoute
  '/assembly-dashboard': typeof AssemblyDashboardRoute
  '/assembly-finished-goods': typeof AssemblyFinishedGoodsRoute
  '/assembly-material-consumption': typeof AssemblyMaterialConsumptionRoute
  '/assembly-material-issues': typeof AssemblyMaterialIssuesRoute
  '/assembly-material-requests': typeof AssemblyMaterialRequestsRoute
  '/assembly-material-requirements': typeof AssemblyMaterialRequirementsRoute
  '/assembly-material-reservations': typeof AssemblyMaterialReservationsRoute
  '/assembly-orders': typeof AssemblyOrdersRoute
  '/assembly-progress': typeof AssemblyProgressRoute
  '/assembly-quality-inspection': typeof AssemblyQualityInspectionRoute
  '/assembly-reports': typeof AssemblyReportsRoute
  '/assembly-rework': typeof AssemblyReworkRoute
  '/assembly-scrap-wastage': typeof AssemblyScrapWastageRoute
  '/assembly-work-orders': typeof AssemblyWorkOrdersRoute
  '/assembly-workforce': typeof AssemblyWorkforceRoute
  '/damage-claims': typeof DamageClaimsRoute
  '/dock-assignment': typeof DockAssignmentRoute
  '/dock-management': typeof DockManagementRoute
  '/dock-master': typeof DockMasterRoute
  '/driver-verification': typeof DriverVerificationRoute
  '/finance-dashboard': typeof FinanceDashboardRoute
  '/gate-dashboard': typeof GateDashboardRoute
  '/gate-entry': typeof GateEntryRoute
  '/grn': typeof GrnRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/master-data': typeof MasterDataRoute
  '/material-data': typeof MaterialDataRoute
  '/new-supplier': typeof NewSupplierRoute
  '/notifications': typeof NotificationsRoute
  '/pick-tasks': typeof PickTasksRoute
  '/procurement-dashboard': typeof ProcurementDashboardRoute
  '/purchase-order': typeof PurchaseOrderRoute
  '/putaway-tasks': typeof PutawayTasksRoute
  '/receiving': typeof ReceivingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/submit-quotation': typeof SubmitQuotationRoute
  '/supplier-dashboard': typeof SupplierDashboardRoute
  '/unscheduled-arrivals': typeof UnscheduledArrivalsRoute
  '/vehicle-exit': typeof VehicleExitRoute
  '/vehicle-queue': typeof VehicleQueueRoute
  '/vehicle-verification': typeof VehicleVerificationRoute
  '/warehouse-dashboard': typeof WarehouseDashboardRoute
  '/warehouse-storage': typeof WarehouseStorageRoute
  '/finance/approvals': typeof FinanceApprovalsRouteWithChildren
  '/procurement/asns': typeof ProcurementAsnsRouteWithChildren
  '/procurement/material-requests': typeof ProcurementMaterialRequestsRoute
  '/procurement/new-rfq': typeof ProcurementNewRfqRoute
  '/procurement/purchase-orders': typeof ProcurementPurchaseOrdersRoute
  '/procurement/quality-issues': typeof ProcurementQualityIssuesRoute
  '/procurement/quotations': typeof ProcurementQuotationsRoute
  '/procurement/rfqs': typeof ProcurementRfqsRoute
  '/supplier/$supplierId': typeof SupplierSupplierIdRoute
  '/supplier/quality-issues': typeof SupplierQualityIssuesRoute
  '/warehouse/material-requests': typeof WarehouseMaterialRequestsRoute
  '/warehouse/materials': typeof WarehouseMaterialsRoute
  '/finance/approvals/$approvalId': typeof FinanceApprovalsApprovalIdRoute
  '/procurement/asns/$asnId': typeof ProcurementAsnsAsnIdRoute
  '/supplier/asns/new': typeof SupplierAsnsNewRoute
  '/finance/approvals/': typeof FinanceApprovalsIndexRoute
  '/procurement/asns/': typeof ProcurementAsnsIndexRoute
  '/finance/approvals/compare/$rfqId': typeof FinanceApprovalsCompareRfqIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-arrival': typeof AcceptArrivalRoute
  '/arrival-success': typeof ArrivalSuccessRoute
  '/assembly-dashboard': typeof AssemblyDashboardRoute
  '/assembly-finished-goods': typeof AssemblyFinishedGoodsRoute
  '/assembly-material-consumption': typeof AssemblyMaterialConsumptionRoute
  '/assembly-material-issues': typeof AssemblyMaterialIssuesRoute
  '/assembly-material-requests': typeof AssemblyMaterialRequestsRoute
  '/assembly-material-requirements': typeof AssemblyMaterialRequirementsRoute
  '/assembly-material-reservations': typeof AssemblyMaterialReservationsRoute
  '/assembly-orders': typeof AssemblyOrdersRoute
  '/assembly-progress': typeof AssemblyProgressRoute
  '/assembly-quality-inspection': typeof AssemblyQualityInspectionRoute
  '/assembly-reports': typeof AssemblyReportsRoute
  '/assembly-rework': typeof AssemblyReworkRoute
  '/assembly-scrap-wastage': typeof AssemblyScrapWastageRoute
  '/assembly-work-orders': typeof AssemblyWorkOrdersRoute
  '/assembly-workforce': typeof AssemblyWorkforceRoute
  '/damage-claims': typeof DamageClaimsRoute
  '/dock-assignment': typeof DockAssignmentRoute
  '/dock-management': typeof DockManagementRoute
  '/dock-master': typeof DockMasterRoute
  '/driver-verification': typeof DriverVerificationRoute
  '/finance-dashboard': typeof FinanceDashboardRoute
  '/gate-dashboard': typeof GateDashboardRoute
  '/gate-entry': typeof GateEntryRoute
  '/grn': typeof GrnRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/master-data': typeof MasterDataRoute
  '/material-data': typeof MaterialDataRoute
  '/new-supplier': typeof NewSupplierRoute
  '/notifications': typeof NotificationsRoute
  '/pick-tasks': typeof PickTasksRoute
  '/procurement-dashboard': typeof ProcurementDashboardRoute
  '/purchase-order': typeof PurchaseOrderRoute
  '/putaway-tasks': typeof PutawayTasksRoute
  '/receiving': typeof ReceivingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/submit-quotation': typeof SubmitQuotationRoute
  '/supplier-dashboard': typeof SupplierDashboardRoute
  '/unscheduled-arrivals': typeof UnscheduledArrivalsRoute
  '/vehicle-exit': typeof VehicleExitRoute
  '/vehicle-queue': typeof VehicleQueueRoute
  '/vehicle-verification': typeof VehicleVerificationRoute
  '/warehouse-dashboard': typeof WarehouseDashboardRoute
  '/warehouse-storage': typeof WarehouseStorageRoute
  '/procurement/material-requests': typeof ProcurementMaterialRequestsRoute
  '/procurement/new-rfq': typeof ProcurementNewRfqRoute
  '/procurement/purchase-orders': typeof ProcurementPurchaseOrdersRoute
  '/procurement/quality-issues': typeof ProcurementQualityIssuesRoute
  '/procurement/quotations': typeof ProcurementQuotationsRoute
  '/procurement/rfqs': typeof ProcurementRfqsRoute
  '/supplier/$supplierId': typeof SupplierSupplierIdRoute
  '/supplier/quality-issues': typeof SupplierQualityIssuesRoute
  '/warehouse/material-requests': typeof WarehouseMaterialRequestsRoute
  '/warehouse/materials': typeof WarehouseMaterialsRoute
  '/finance/approvals/$approvalId': typeof FinanceApprovalsApprovalIdRoute
  '/procurement/asns/$asnId': typeof ProcurementAsnsAsnIdRoute
  '/supplier/asns/new': typeof SupplierAsnsNewRoute
  '/finance/approvals': typeof FinanceApprovalsIndexRoute
  '/procurement/asns': typeof ProcurementAsnsIndexRoute
  '/finance/approvals/compare/$rfqId': typeof FinanceApprovalsCompareRfqIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-arrival': typeof AcceptArrivalRoute
  '/arrival-success': typeof ArrivalSuccessRoute
  '/assembly-dashboard': typeof AssemblyDashboardRoute
  '/assembly-finished-goods': typeof AssemblyFinishedGoodsRoute
  '/assembly-material-consumption': typeof AssemblyMaterialConsumptionRoute
  '/assembly-material-issues': typeof AssemblyMaterialIssuesRoute
  '/assembly-material-requests': typeof AssemblyMaterialRequestsRoute
  '/assembly-material-requirements': typeof AssemblyMaterialRequirementsRoute
  '/assembly-material-reservations': typeof AssemblyMaterialReservationsRoute
  '/assembly-orders': typeof AssemblyOrdersRoute
  '/assembly-progress': typeof AssemblyProgressRoute
  '/assembly-quality-inspection': typeof AssemblyQualityInspectionRoute
  '/assembly-reports': typeof AssemblyReportsRoute
  '/assembly-rework': typeof AssemblyReworkRoute
  '/assembly-scrap-wastage': typeof AssemblyScrapWastageRoute
  '/assembly-work-orders': typeof AssemblyWorkOrdersRoute
  '/assembly-workforce': typeof AssemblyWorkforceRoute
  '/damage-claims': typeof DamageClaimsRoute
  '/dock-assignment': typeof DockAssignmentRoute
  '/dock-management': typeof DockManagementRoute
  '/dock-master': typeof DockMasterRoute
  '/driver-verification': typeof DriverVerificationRoute
  '/finance-dashboard': typeof FinanceDashboardRoute
  '/gate-dashboard': typeof GateDashboardRoute
  '/gate-entry': typeof GateEntryRoute
  '/grn': typeof GrnRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/master-data': typeof MasterDataRoute
  '/material-data': typeof MaterialDataRoute
  '/new-supplier': typeof NewSupplierRoute
  '/notifications': typeof NotificationsRoute
  '/pick-tasks': typeof PickTasksRoute
  '/procurement-dashboard': typeof ProcurementDashboardRoute
  '/purchase-order': typeof PurchaseOrderRoute
  '/putaway-tasks': typeof PutawayTasksRoute
  '/receiving': typeof ReceivingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/submit-quotation': typeof SubmitQuotationRoute
  '/supplier-dashboard': typeof SupplierDashboardRoute
  '/unscheduled-arrivals': typeof UnscheduledArrivalsRoute
  '/vehicle-exit': typeof VehicleExitRoute
  '/vehicle-queue': typeof VehicleQueueRoute
  '/vehicle-verification': typeof VehicleVerificationRoute
  '/warehouse-dashboard': typeof WarehouseDashboardRoute
  '/warehouse-storage': typeof WarehouseStorageRoute
  '/finance/approvals': typeof FinanceApprovalsRouteWithChildren
  '/procurement/asns': typeof ProcurementAsnsRouteWithChildren
  '/procurement/material-requests': typeof ProcurementMaterialRequestsRoute
  '/procurement/new-rfq': typeof ProcurementNewRfqRoute
  '/procurement/purchase-orders': typeof ProcurementPurchaseOrdersRoute
  '/procurement/quality-issues': typeof ProcurementQualityIssuesRoute
  '/procurement/quotations': typeof ProcurementQuotationsRoute
  '/procurement/rfqs': typeof ProcurementRfqsRoute
  '/supplier/$supplierId': typeof SupplierSupplierIdRoute
  '/supplier/quality-issues': typeof SupplierQualityIssuesRoute
  '/warehouse/material-requests': typeof WarehouseMaterialRequestsRoute
  '/warehouse/materials': typeof WarehouseMaterialsRoute
  '/finance/approvals/$approvalId': typeof FinanceApprovalsApprovalIdRoute
  '/procurement/asns/$asnId': typeof ProcurementAsnsAsnIdRoute
  '/supplier/asns/new': typeof SupplierAsnsNewRoute
  '/finance/approvals/': typeof FinanceApprovalsIndexRoute
  '/procurement/asns/': typeof ProcurementAsnsIndexRoute
  '/finance/approvals/compare/$rfqId': typeof FinanceApprovalsCompareRfqIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-arrival'
    | '/arrival-success'
    | '/assembly-dashboard'
    | '/assembly-finished-goods'
    | '/assembly-material-consumption'
    | '/assembly-material-issues'
    | '/assembly-material-requests'
    | '/assembly-material-requirements'
    | '/assembly-material-reservations'
    | '/assembly-orders'
    | '/assembly-progress'
    | '/assembly-quality-inspection'
    | '/assembly-reports'
    | '/assembly-rework'
    | '/assembly-scrap-wastage'
    | '/assembly-work-orders'
    | '/assembly-workforce'
    | '/damage-claims'
    | '/dock-assignment'
    | '/dock-management'
    | '/dock-master'
    | '/driver-verification'
    | '/finance-dashboard'
    | '/gate-dashboard'
    | '/gate-entry'
    | '/grn'
    | '/inventory'
    | '/login'
    | '/master-data'
    | '/material-data'
    | '/new-supplier'
    | '/notifications'
    | '/pick-tasks'
    | '/procurement-dashboard'
    | '/purchase-order'
    | '/putaway-tasks'
    | '/receiving'
    | '/reports'
    | '/settings'
    | '/submit-quotation'
    | '/supplier-dashboard'
    | '/unscheduled-arrivals'
    | '/vehicle-exit'
    | '/vehicle-queue'
    | '/vehicle-verification'
    | '/warehouse-dashboard'
    | '/warehouse-storage'
    | '/finance/approvals'
    | '/procurement/asns'
    | '/procurement/material-requests'
    | '/procurement/new-rfq'
    | '/procurement/purchase-orders'
    | '/procurement/quality-issues'
    | '/procurement/quotations'
    | '/procurement/rfqs'
    | '/supplier/$supplierId'
    | '/supplier/quality-issues'
    | '/warehouse/material-requests'
    | '/warehouse/materials'
    | '/finance/approvals/$approvalId'
    | '/procurement/asns/$asnId'
    | '/supplier/asns/new'
    | '/finance/approvals/'
    | '/procurement/asns/'
    | '/finance/approvals/compare/$rfqId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-arrival'
    | '/arrival-success'
    | '/assembly-dashboard'
    | '/assembly-finished-goods'
    | '/assembly-material-consumption'
    | '/assembly-material-issues'
    | '/assembly-material-requests'
    | '/assembly-material-requirements'
    | '/assembly-material-reservations'
    | '/assembly-orders'
    | '/assembly-progress'
    | '/assembly-quality-inspection'
    | '/assembly-reports'
    | '/assembly-rework'
    | '/assembly-scrap-wastage'
    | '/assembly-work-orders'
    | '/assembly-workforce'
    | '/damage-claims'
    | '/dock-assignment'
    | '/dock-management'
    | '/dock-master'
    | '/driver-verification'
    | '/finance-dashboard'
    | '/gate-dashboard'
    | '/gate-entry'
    | '/grn'
    | '/inventory'
    | '/login'
    | '/master-data'
    | '/material-data'
    | '/new-supplier'
    | '/notifications'
    | '/pick-tasks'
    | '/procurement-dashboard'
    | '/purchase-order'
    | '/putaway-tasks'
    | '/receiving'
    | '/reports'
    | '/settings'
    | '/submit-quotation'
    | '/supplier-dashboard'
    | '/unscheduled-arrivals'
    | '/vehicle-exit'
    | '/vehicle-queue'
    | '/vehicle-verification'
    | '/warehouse-dashboard'
    | '/warehouse-storage'
    | '/procurement/material-requests'
    | '/procurement/new-rfq'
    | '/procurement/purchase-orders'
    | '/procurement/quality-issues'
    | '/procurement/quotations'
    | '/procurement/rfqs'
    | '/supplier/$supplierId'
    | '/supplier/quality-issues'
    | '/warehouse/material-requests'
    | '/warehouse/materials'
    | '/finance/approvals/$approvalId'
    | '/procurement/asns/$asnId'
    | '/supplier/asns/new'
    | '/finance/approvals'
    | '/procurement/asns'
    | '/finance/approvals/compare/$rfqId'
  id:
    | '__root__'
    | '/'
    | '/accept-arrival'
    | '/arrival-success'
    | '/assembly-dashboard'
    | '/assembly-finished-goods'
    | '/assembly-material-consumption'
    | '/assembly-material-issues'
    | '/assembly-material-requests'
    | '/assembly-material-requirements'
    | '/assembly-material-reservations'
    | '/assembly-orders'
    | '/assembly-progress'
    | '/assembly-quality-inspection'
    | '/assembly-reports'
    | '/assembly-rework'
    | '/assembly-scrap-wastage'
    | '/assembly-work-orders'
    | '/assembly-workforce'
    | '/damage-claims'
    | '/dock-assignment'
    | '/dock-management'
    | '/dock-master'
    | '/driver-verification'
    | '/finance-dashboard'
    | '/gate-dashboard'
    | '/gate-entry'
    | '/grn'
    | '/inventory'
    | '/login'
    | '/master-data'
    | '/material-data'
    | '/new-supplier'
    | '/notifications'
    | '/pick-tasks'
    | '/procurement-dashboard'
    | '/purchase-order'
    | '/putaway-tasks'
    | '/receiving'
    | '/reports'
    | '/settings'
    | '/submit-quotation'
    | '/supplier-dashboard'
    | '/unscheduled-arrivals'
    | '/vehicle-exit'
    | '/vehicle-queue'
    | '/vehicle-verification'
    | '/warehouse-dashboard'
    | '/warehouse-storage'
    | '/finance/approvals'
    | '/procurement/asns'
    | '/procurement/material-requests'
    | '/procurement/new-rfq'
    | '/procurement/purchase-orders'
    | '/procurement/quality-issues'
    | '/procurement/quotations'
    | '/procurement/rfqs'
    | '/supplier/$supplierId'
    | '/supplier/quality-issues'
    | '/warehouse/material-requests'
    | '/warehouse/materials'
    | '/finance/approvals/$approvalId'
    | '/procurement/asns/$asnId'
    | '/supplier/asns/new'
    | '/finance/approvals/'
    | '/procurement/asns/'
    | '/finance/approvals/compare/$rfqId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptArrivalRoute: typeof AcceptArrivalRoute
  ArrivalSuccessRoute: typeof ArrivalSuccessRoute
  AssemblyDashboardRoute: typeof AssemblyDashboardRoute
  AssemblyFinishedGoodsRoute: typeof AssemblyFinishedGoodsRoute
  AssemblyMaterialConsumptionRoute: typeof AssemblyMaterialConsumptionRoute
  AssemblyMaterialIssuesRoute: typeof AssemblyMaterialIssuesRoute
  AssemblyMaterialRequestsRoute: typeof AssemblyMaterialRequestsRoute
  AssemblyMaterialRequirementsRoute: typeof AssemblyMaterialRequirementsRoute
  AssemblyMaterialReservationsRoute: typeof AssemblyMaterialReservationsRoute
  AssemblyOrdersRoute: typeof AssemblyOrdersRoute
  AssemblyProgressRoute: typeof AssemblyProgressRoute
  AssemblyQualityInspectionRoute: typeof AssemblyQualityInspectionRoute
  AssemblyReportsRoute: typeof AssemblyReportsRoute
  AssemblyReworkRoute: typeof AssemblyReworkRoute
  AssemblyScrapWastageRoute: typeof AssemblyScrapWastageRoute
  AssemblyWorkOrdersRoute: typeof AssemblyWorkOrdersRoute
  AssemblyWorkforceRoute: typeof AssemblyWorkforceRoute
  DamageClaimsRoute: typeof DamageClaimsRoute
  DockAssignmentRoute: typeof DockAssignmentRoute
  DockManagementRoute: typeof DockManagementRoute
  DockMasterRoute: typeof DockMasterRoute
  DriverVerificationRoute: typeof DriverVerificationRoute
  FinanceDashboardRoute: typeof FinanceDashboardRoute
  GateDashboardRoute: typeof GateDashboardRoute
  GateEntryRoute: typeof GateEntryRoute
  GrnRoute: typeof GrnRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MasterDataRoute: typeof MasterDataRoute
  MaterialDataRoute: typeof MaterialDataRoute
  NewSupplierRoute: typeof NewSupplierRoute
  NotificationsRoute: typeof NotificationsRoute
  PickTasksRoute: typeof PickTasksRoute
  ProcurementDashboardRoute: typeof ProcurementDashboardRoute
  PurchaseOrderRoute: typeof PurchaseOrderRoute
  PutawayTasksRoute: typeof PutawayTasksRoute
  ReceivingRoute: typeof ReceivingRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SubmitQuotationRoute: typeof SubmitQuotationRoute
  SupplierDashboardRoute: typeof SupplierDashboardRoute
  UnscheduledArrivalsRoute: typeof UnscheduledArrivalsRoute
  VehicleExitRoute: typeof VehicleExitRoute
  VehicleQueueRoute: typeof VehicleQueueRoute
  VehicleVerificationRoute: typeof VehicleVerificationRoute
  WarehouseDashboardRoute: typeof WarehouseDashboardRoute
  WarehouseStorageRoute: typeof WarehouseStorageRoute
  FinanceApprovalsRoute: typeof FinanceApprovalsRouteWithChildren
  ProcurementAsnsRoute: typeof ProcurementAsnsRouteWithChildren
  ProcurementMaterialRequestsRoute: typeof ProcurementMaterialRequestsRoute
  ProcurementNewRfqRoute: typeof ProcurementNewRfqRoute
  ProcurementPurchaseOrdersRoute: typeof ProcurementPurchaseOrdersRoute
  ProcurementQualityIssuesRoute: typeof ProcurementQualityIssuesRoute
  ProcurementQuotationsRoute: typeof ProcurementQuotationsRoute
  ProcurementRfqsRoute: typeof ProcurementRfqsRoute
  SupplierSupplierIdRoute: typeof SupplierSupplierIdRoute
  SupplierQualityIssuesRoute: typeof SupplierQualityIssuesRoute
  WarehouseMaterialRequestsRoute: typeof WarehouseMaterialRequestsRoute
  WarehouseMaterialsRoute: typeof WarehouseMaterialsRoute
  SupplierAsnsNewRoute: typeof SupplierAsnsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-arrival': {
      id: '/accept-arrival'
      path: '/accept-arrival'
      fullPath: '/accept-arrival'
      preLoaderRoute: typeof AcceptArrivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrival-success': {
      id: '/arrival-success'
      path: '/arrival-success'
      fullPath: '/arrival-success'
      preLoaderRoute: typeof ArrivalSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly-dashboard': {
      id: '/assembly-dashboard'
      path: '/assembly-dashboard'
      fullPath: '/assembly-dashboard'
      preLoaderRoute: typeof AssemblyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly-finished-goods': {
      id: '/assembly-finished-goods'
      path: '/assembly-finished-goods'
      fullPath: '/assembly-finished-goods'
      preLoaderRoute: typeof AssemblyFinishedGoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly-material-consumption': {
      id: '/assembly-material-consumption'
      path: '/assembly-material-consumption'
      fullPath: '/assembly-material-consumption'
      preLoaderRoute: typeof AssemblyMaterialConsumptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly-material-issues': {
      id: '/assembly-material-issues'
      path: '/assembly-material-issues'
      fullPath: '/assembly-material-issues'
      preLoaderRoute: typeof AssemblyMaterialIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly-material-requests': {
      id: '/assembly-material-requests'
      path: '/assembly-material-requests'
      fullPath: '/assembly-material-requests'
      preLoaderRoute: typeof AssemblyMaterialRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly-material-requirements': {
      id: '/assembly-material-requirements'
      path: '/assembly-material-requirements'
      fullPath: '/assembly-material-requirements'
      preLoaderRoute: typeof AssemblyMaterialRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly-material-reservations': {
      id: '/assembly-material-reservations'
      path: '/assembly-material-reservations'
      fullPath: '/assembly-material-reservations'
      preLoaderRoute: typeof AssemblyMaterialReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly-orders': {
      id: '/assembly-orders'
      path: '/assembly-orders'
      fullPath: '/assembly-orders'
      preLoaderRoute: typeof AssemblyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly-progress': {
      id: '/assembly-progress'
      path: '/assembly-progress'
      fullPath: '/assembly-progress'
      preLoaderRoute: typeof AssemblyProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly-quality-inspection': {
      id: '/assembly-quality-inspection'
      path: '/assembly-quality-inspection'
      fullPath: '/assembly-quality-inspection'
      preLoaderRoute: typeof AssemblyQualityInspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly-reports': {
      id: '/assembly-reports'
      path: '/assembly-reports'
      fullPath: '/assembly-reports'
      preLoaderRoute: typeof AssemblyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly-rework': {
      id: '/assembly-rework'
      path: '/assembly-rework'
      fullPath: '/assembly-rework'
      preLoaderRoute: typeof AssemblyReworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly-scrap-wastage': {
      id: '/assembly-scrap-wastage'
      path: '/assembly-scrap-wastage'
      fullPath: '/assembly-scrap-wastage'
      preLoaderRoute: typeof AssemblyScrapWastageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly-work-orders': {
      id: '/assembly-work-orders'
      path: '/assembly-work-orders'
      fullPath: '/assembly-work-orders'
      preLoaderRoute: typeof AssemblyWorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assembly-workforce': {
      id: '/assembly-workforce'
      path: '/assembly-workforce'
      fullPath: '/assembly-workforce'
      preLoaderRoute: typeof AssemblyWorkforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damage-claims': {
      id: '/damage-claims'
      path: '/damage-claims'
      fullPath: '/damage-claims'
      preLoaderRoute: typeof DamageClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dock-assignment': {
      id: '/dock-assignment'
      path: '/dock-assignment'
      fullPath: '/dock-assignment'
      preLoaderRoute: typeof DockAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dock-management': {
      id: '/dock-management'
      path: '/dock-management'
      fullPath: '/dock-management'
      preLoaderRoute: typeof DockManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dock-master': {
      id: '/dock-master'
      path: '/dock-master'
      fullPath: '/dock-master'
      preLoaderRoute: typeof DockMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-verification': {
      id: '/driver-verification'
      path: '/driver-verification'
      fullPath: '/driver-verification'
      preLoaderRoute: typeof DriverVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-dashboard': {
      id: '/finance-dashboard'
      path: '/finance-dashboard'
      fullPath: '/finance-dashboard'
      preLoaderRoute: typeof FinanceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate-dashboard': {
      id: '/gate-dashboard'
      path: '/gate-dashboard'
      fullPath: '/gate-dashboard'
      preLoaderRoute: typeof GateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate-entry': {
      id: '/gate-entry'
      path: '/gate-entry'
      fullPath: '/gate-entry'
      preLoaderRoute: typeof GateEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grn': {
      id: '/grn'
      path: '/grn'
      fullPath: '/grn'
      preLoaderRoute: typeof GrnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data': {
      id: '/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof MasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-data': {
      id: '/material-data'
      path: '/material-data'
      fullPath: '/material-data'
      preLoaderRoute: typeof MaterialDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-supplier': {
      id: '/new-supplier'
      path: '/new-supplier'
      fullPath: '/new-supplier'
      preLoaderRoute: typeof NewSupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick-tasks': {
      id: '/pick-tasks'
      path: '/pick-tasks'
      fullPath: '/pick-tasks'
      preLoaderRoute: typeof PickTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement-dashboard': {
      id: '/procurement-dashboard'
      path: '/procurement-dashboard'
      fullPath: '/procurement-dashboard'
      preLoaderRoute: typeof ProcurementDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-order': {
      id: '/purchase-order'
      path: '/purchase-order'
      fullPath: '/purchase-order'
      preLoaderRoute: typeof PurchaseOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/putaway-tasks': {
      id: '/putaway-tasks'
      path: '/putaway-tasks'
      fullPath: '/putaway-tasks'
      preLoaderRoute: typeof PutawayTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receiving': {
      id: '/receiving'
      path: '/receiving'
      fullPath: '/receiving'
      preLoaderRoute: typeof ReceivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-quotation': {
      id: '/submit-quotation'
      path: '/submit-quotation'
      fullPath: '/submit-quotation'
      preLoaderRoute: typeof SubmitQuotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-dashboard': {
      id: '/supplier-dashboard'
      path: '/supplier-dashboard'
      fullPath: '/supplier-dashboard'
      preLoaderRoute: typeof SupplierDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unscheduled-arrivals': {
      id: '/unscheduled-arrivals'
      path: '/unscheduled-arrivals'
      fullPath: '/unscheduled-arrivals'
      preLoaderRoute: typeof UnscheduledArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-exit': {
      id: '/vehicle-exit'
      path: '/vehicle-exit'
      fullPath: '/vehicle-exit'
      preLoaderRoute: typeof VehicleExitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-queue': {
      id: '/vehicle-queue'
      path: '/vehicle-queue'
      fullPath: '/vehicle-queue'
      preLoaderRoute: typeof VehicleQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-verification': {
      id: '/vehicle-verification'
      path: '/vehicle-verification'
      fullPath: '/vehicle-verification'
      preLoaderRoute: typeof VehicleVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse-dashboard': {
      id: '/warehouse-dashboard'
      path: '/warehouse-dashboard'
      fullPath: '/warehouse-dashboard'
      preLoaderRoute: typeof WarehouseDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse-storage': {
      id: '/warehouse-storage'
      path: '/warehouse-storage'
      fullPath: '/warehouse-storage'
      preLoaderRoute: typeof WarehouseStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/approvals': {
      id: '/finance/approvals'
      path: '/finance/approvals'
      fullPath: '/finance/approvals'
      preLoaderRoute: typeof FinanceApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/asns': {
      id: '/procurement/asns'
      path: '/procurement/asns'
      fullPath: '/procurement/asns'
      preLoaderRoute: typeof ProcurementAsnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/material-requests': {
      id: '/procurement/material-requests'
      path: '/procurement/material-requests'
      fullPath: '/procurement/material-requests'
      preLoaderRoute: typeof ProcurementMaterialRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/new-rfq': {
      id: '/procurement/new-rfq'
      path: '/procurement/new-rfq'
      fullPath: '/procurement/new-rfq'
      preLoaderRoute: typeof ProcurementNewRfqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/purchase-orders': {
      id: '/procurement/purchase-orders'
      path: '/procurement/purchase-orders'
      fullPath: '/procurement/purchase-orders'
      preLoaderRoute: typeof ProcurementPurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/quality-issues': {
      id: '/procurement/quality-issues'
      path: '/procurement/quality-issues'
      fullPath: '/procurement/quality-issues'
      preLoaderRoute: typeof ProcurementQualityIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/quotations': {
      id: '/procurement/quotations'
      path: '/procurement/quotations'
      fullPath: '/procurement/quotations'
      preLoaderRoute: typeof ProcurementQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/rfqs': {
      id: '/procurement/rfqs'
      path: '/procurement/rfqs'
      fullPath: '/procurement/rfqs'
      preLoaderRoute: typeof ProcurementRfqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/$supplierId': {
      id: '/supplier/$supplierId'
      path: '/supplier/$supplierId'
      fullPath: '/supplier/$supplierId'
      preLoaderRoute: typeof SupplierSupplierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/quality-issues': {
      id: '/supplier/quality-issues'
      path: '/supplier/quality-issues'
      fullPath: '/supplier/quality-issues'
      preLoaderRoute: typeof SupplierQualityIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/material-requests': {
      id: '/warehouse/material-requests'
      path: '/warehouse/material-requests'
      fullPath: '/warehouse/material-requests'
      preLoaderRoute: typeof WarehouseMaterialRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/materials': {
      id: '/warehouse/materials'
      path: '/warehouse/materials'
      fullPath: '/warehouse/materials'
      preLoaderRoute: typeof WarehouseMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/approvals/': {
      id: '/finance/approvals/'
      path: '/'
      fullPath: '/finance/approvals/'
      preLoaderRoute: typeof FinanceApprovalsIndexRouteImport
      parentRoute: typeof FinanceApprovalsRoute
    }
    '/finance/approvals/$approvalId': {
      id: '/finance/approvals/$approvalId'
      path: '/$approvalId'
      fullPath: '/finance/approvals/$approvalId'
      preLoaderRoute: typeof FinanceApprovalsApprovalIdRouteImport
      parentRoute: typeof FinanceApprovalsRoute
    }
    '/procurement/asns/': {
      id: '/procurement/asns/'
      path: '/'
      fullPath: '/procurement/asns/'
      preLoaderRoute: typeof ProcurementAsnsIndexRouteImport
      parentRoute: typeof ProcurementAsnsRoute
    }
    '/procurement/asns/$asnId': {
      id: '/procurement/asns/$asnId'
      path: '/$asnId'
      fullPath: '/procurement/asns/$asnId'
      preLoaderRoute: typeof ProcurementAsnsAsnIdRouteImport
      parentRoute: typeof ProcurementAsnsRoute
    }
    '/supplier/asns/new': {
      id: '/supplier/asns/new'
      path: '/supplier/asns/new'
      fullPath: '/supplier/asns/new'
      preLoaderRoute: typeof SupplierAsnsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/approvals/compare/$rfqId': {
      id: '/finance/approvals/compare/$rfqId'
      path: '/compare/$rfqId'
      fullPath: '/finance/approvals/compare/$rfqId'
      preLoaderRoute: typeof FinanceApprovalsCompareRfqIdRouteImport
      parentRoute: typeof FinanceApprovalsRoute
    }
  }
}

interface FinanceApprovalsRouteChildren {
  FinanceApprovalsApprovalIdRoute: typeof FinanceApprovalsApprovalIdRoute
  FinanceApprovalsIndexRoute: typeof FinanceApprovalsIndexRoute
  FinanceApprovalsCompareRfqIdRoute: typeof FinanceApprovalsCompareRfqIdRoute
}

const FinanceApprovalsRouteChildren: FinanceApprovalsRouteChildren = {
  FinanceApprovalsApprovalIdRoute: FinanceApprovalsApprovalIdRoute,
  FinanceApprovalsIndexRoute: FinanceApprovalsIndexRoute,
  FinanceApprovalsCompareRfqIdRoute: FinanceApprovalsCompareRfqIdRoute,
}

const FinanceApprovalsRouteWithChildren =
  FinanceApprovalsRoute._addFileChildren(FinanceApprovalsRouteChildren)

interface ProcurementAsnsRouteChildren {
  ProcurementAsnsAsnIdRoute: typeof ProcurementAsnsAsnIdRoute
  ProcurementAsnsIndexRoute: typeof ProcurementAsnsIndexRoute
}

const ProcurementAsnsRouteChildren: ProcurementAsnsRouteChildren = {
  ProcurementAsnsAsnIdRoute: ProcurementAsnsAsnIdRoute,
  ProcurementAsnsIndexRoute: ProcurementAsnsIndexRoute,
}

const ProcurementAsnsRouteWithChildren = ProcurementAsnsRoute._addFileChildren(
  ProcurementAsnsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptArrivalRoute: AcceptArrivalRoute,
  ArrivalSuccessRoute: ArrivalSuccessRoute,
  AssemblyDashboardRoute: AssemblyDashboardRoute,
  AssemblyFinishedGoodsRoute: AssemblyFinishedGoodsRoute,
  AssemblyMaterialConsumptionRoute: AssemblyMaterialConsumptionRoute,
  AssemblyMaterialIssuesRoute: AssemblyMaterialIssuesRoute,
  AssemblyMaterialRequestsRoute: AssemblyMaterialRequestsRoute,
  AssemblyMaterialRequirementsRoute: AssemblyMaterialRequirementsRoute,
  AssemblyMaterialReservationsRoute: AssemblyMaterialReservationsRoute,
  AssemblyOrdersRoute: AssemblyOrdersRoute,
  AssemblyProgressRoute: AssemblyProgressRoute,
  AssemblyQualityInspectionRoute: AssemblyQualityInspectionRoute,
  AssemblyReportsRoute: AssemblyReportsRoute,
  AssemblyReworkRoute: AssemblyReworkRoute,
  AssemblyScrapWastageRoute: AssemblyScrapWastageRoute,
  AssemblyWorkOrdersRoute: AssemblyWorkOrdersRoute,
  AssemblyWorkforceRoute: AssemblyWorkforceRoute,
  DamageClaimsRoute: DamageClaimsRoute,
  DockAssignmentRoute: DockAssignmentRoute,
  DockManagementRoute: DockManagementRoute,
  DockMasterRoute: DockMasterRoute,
  DriverVerificationRoute: DriverVerificationRoute,
  FinanceDashboardRoute: FinanceDashboardRoute,
  GateDashboardRoute: GateDashboardRoute,
  GateEntryRoute: GateEntryRoute,
  GrnRoute: GrnRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MasterDataRoute: MasterDataRoute,
  MaterialDataRoute: MaterialDataRoute,
  NewSupplierRoute: NewSupplierRoute,
  NotificationsRoute: NotificationsRoute,
  PickTasksRoute: PickTasksRoute,
  ProcurementDashboardRoute: ProcurementDashboardRoute,
  PurchaseOrderRoute: PurchaseOrderRoute,
  PutawayTasksRoute: PutawayTasksRoute,
  ReceivingRoute: ReceivingRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SubmitQuotationRoute: SubmitQuotationRoute,
  SupplierDashboardRoute: SupplierDashboardRoute,
  UnscheduledArrivalsRoute: UnscheduledArrivalsRoute,
  VehicleExitRoute: VehicleExitRoute,
  VehicleQueueRoute: VehicleQueueRoute,
  VehicleVerificationRoute: VehicleVerificationRoute,
  WarehouseDashboardRoute: WarehouseDashboardRoute,
  WarehouseStorageRoute: WarehouseStorageRoute,
  FinanceApprovalsRoute: FinanceApprovalsRouteWithChildren,
  ProcurementAsnsRoute: ProcurementAsnsRouteWithChildren,
  ProcurementMaterialRequestsRoute: ProcurementMaterialRequestsRoute,
  ProcurementNewRfqRoute: ProcurementNewRfqRoute,
  ProcurementPurchaseOrdersRoute: ProcurementPurchaseOrdersRoute,
  ProcurementQualityIssuesRoute: ProcurementQualityIssuesRoute,
  ProcurementQuotationsRoute: ProcurementQuotationsRoute,
  ProcurementRfqsRoute: ProcurementRfqsRoute,
  SupplierSupplierIdRoute: SupplierSupplierIdRoute,
  SupplierQualityIssuesRoute: SupplierQualityIssuesRoute,
  WarehouseMaterialRequestsRoute: WarehouseMaterialRequestsRoute,
  WarehouseMaterialsRoute: WarehouseMaterialsRoute,
  SupplierAsnsNewRoute: SupplierAsnsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
