/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptArrivalRouteImport } from './routes/accept-arrival'
import { Route as ArrivalSuccessRouteImport } from './routes/arrival-success'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DockAssignmentRouteImport } from './routes/dock-assignment'
import { Route as DriverVerificationRouteImport } from './routes/driver-verification'
import { Route as FinanceApprovalRouteImport } from './routes/finance-approval'
import { Route as FinanceDashboardRouteImport } from './routes/finance-dashboard'
import { Route as GateEntryRouteImport } from './routes/gate-entry'
import { Route as GrnRouteImport } from './routes/grn'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasterDataRouteImport } from './routes/master-data'
import { Route as NewSupplierRouteImport } from './routes/new-supplier'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProcurementDashboardRouteImport } from './routes/procurement-dashboard'
import { Route as PurchaseOrderRouteImport } from './routes/purchase-order'
import { Route as ReceivingRouteImport } from './routes/receiving'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubmitQuotationRouteImport } from './routes/submit-quotation'
import { Route as SupplierDashboardRouteImport } from './routes/supplier-dashboard'
import { Route as VehicleQueueRouteImport } from './routes/vehicle-queue'
import { Route as VehicleVerificationRouteImport } from './routes/vehicle-verification'
import { Route as ProcurementAsnsRouteImport } from './routes/procurement.asns'
import { Route as ProcurementNewPoRouteImport } from './routes/procurement.new-po'
import { Route as ProcurementNewRfqRouteImport } from './routes/procurement.new-rfq'
import { Route as ProcurementPoDetailRouteImport } from './routes/procurement.po-detail'
import { Route as ProcurementPurchaseOrdersRouteImport } from './routes/procurement.purchase-orders'
import { Route as ProcurementQuotationsRouteImport } from './routes/procurement.quotations'
import { Route as ProcurementRfqsRouteImport } from './routes/procurement.rfqs'
import { Route as SupplierSupplierIdRouteImport } from './routes/supplier.$supplierId'
import { Route as SupplierAsnsNewRouteImport } from './routes/supplier.asns.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptArrivalRoute = AcceptArrivalRouteImport.update({
  id: '/accept-arrival',
  path: '/accept-arrival',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrivalSuccessRoute = ArrivalSuccessRouteImport.update({
  id: '/arrival-success',
  path: '/arrival-success',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DockAssignmentRoute = DockAssignmentRouteImport.update({
  id: '/dock-assignment',
  path: '/dock-assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverVerificationRoute = DriverVerificationRouteImport.update({
  id: '/driver-verification',
  path: '/driver-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceApprovalRoute = FinanceApprovalRouteImport.update({
  id: '/finance-approval',
  path: '/finance-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceDashboardRoute = FinanceDashboardRouteImport.update({
  id: '/finance-dashboard',
  path: '/finance-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GateEntryRoute = GateEntryRouteImport.update({
  id: '/gate-entry',
  path: '/gate-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const GrnRoute = GrnRouteImport.update({
  id: '/grn',
  path: '/grn',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterDataRoute = MasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => rootRouteImport,
} as any)
const NewSupplierRoute = NewSupplierRouteImport.update({
  id: '/new-supplier',
  path: '/new-supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementDashboardRoute = ProcurementDashboardRouteImport.update({
  id: '/procurement-dashboard',
  path: '/procurement-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrderRoute = PurchaseOrderRouteImport.update({
  id: '/purchase-order',
  path: '/purchase-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivingRoute = ReceivingRouteImport.update({
  id: '/receiving',
  path: '/receiving',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitQuotationRoute = SubmitQuotationRouteImport.update({
  id: '/submit-quotation',
  path: '/submit-quotation',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierDashboardRoute = SupplierDashboardRouteImport.update({
  id: '/supplier-dashboard',
  path: '/supplier-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleQueueRoute = VehicleQueueRouteImport.update({
  id: '/vehicle-queue',
  path: '/vehicle-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleVerificationRoute = VehicleVerificationRouteImport.update({
  id: '/vehicle-verification',
  path: '/vehicle-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementAsnsRoute = ProcurementAsnsRouteImport.update({
  id: '/procurement/asns',
  path: '/procurement/asns',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementNewPoRoute = ProcurementNewPoRouteImport.update({
  id: '/procurement/new-po',
  path: '/procurement/new-po',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementNewRfqRoute = ProcurementNewRfqRouteImport.update({
  id: '/procurement/new-rfq',
  path: '/procurement/new-rfq',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementPoDetailRoute = ProcurementPoDetailRouteImport.update({
  id: '/procurement/po-detail',
  path: '/procurement/po-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementPurchaseOrdersRoute =
  ProcurementPurchaseOrdersRouteImport.update({
    id: '/procurement/purchase-orders',
    path: '/procurement/purchase-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProcurementQuotationsRoute = ProcurementQuotationsRouteImport.update({
  id: '/procurement/quotations',
  path: '/procurement/quotations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRfqsRoute = ProcurementRfqsRouteImport.update({
  id: '/procurement/rfqs',
  path: '/procurement/rfqs',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierSupplierIdRoute = SupplierSupplierIdRouteImport.update({
  id: '/supplier/$supplierId',
  path: '/supplier/$supplierId',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierAsnsNewRoute = SupplierAsnsNewRouteImport.update({
  id: '/supplier/asns/new',
  path: '/supplier/asns/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-arrival': typeof AcceptArrivalRoute
  '/arrival-success': typeof ArrivalSuccessRoute
  '/dashboard': typeof DashboardRoute
  '/dock-assignment': typeof DockAssignmentRoute
  '/driver-verification': typeof DriverVerificationRoute
  '/finance-approval': typeof FinanceApprovalRoute
  '/finance-dashboard': typeof FinanceDashboardRoute
  '/gate-entry': typeof GateEntryRoute
  '/grn': typeof GrnRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/master-data': typeof MasterDataRoute
  '/new-supplier': typeof NewSupplierRoute
  '/notifications': typeof NotificationsRoute
  '/procurement-dashboard': typeof ProcurementDashboardRoute
  '/purchase-order': typeof PurchaseOrderRoute
  '/receiving': typeof ReceivingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/submit-quotation': typeof SubmitQuotationRoute
  '/supplier-dashboard': typeof SupplierDashboardRoute
  '/vehicle-queue': typeof VehicleQueueRoute
  '/vehicle-verification': typeof VehicleVerificationRoute
  '/procurement/asns': typeof ProcurementAsnsRoute
  '/procurement/new-po': typeof ProcurementNewPoRoute
  '/procurement/new-rfq': typeof ProcurementNewRfqRoute
  '/procurement/po-detail': typeof ProcurementPoDetailRoute
  '/procurement/purchase-orders': typeof ProcurementPurchaseOrdersRoute
  '/procurement/quotations': typeof ProcurementQuotationsRoute
  '/procurement/rfqs': typeof ProcurementRfqsRoute
  '/supplier/$supplierId': typeof SupplierSupplierIdRoute
  '/supplier/asns/new': typeof SupplierAsnsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-arrival': typeof AcceptArrivalRoute
  '/arrival-success': typeof ArrivalSuccessRoute
  '/dashboard': typeof DashboardRoute
  '/dock-assignment': typeof DockAssignmentRoute
  '/driver-verification': typeof DriverVerificationRoute
  '/finance-approval': typeof FinanceApprovalRoute
  '/finance-dashboard': typeof FinanceDashboardRoute
  '/gate-entry': typeof GateEntryRoute
  '/grn': typeof GrnRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/master-data': typeof MasterDataRoute
  '/new-supplier': typeof NewSupplierRoute
  '/notifications': typeof NotificationsRoute
  '/procurement-dashboard': typeof ProcurementDashboardRoute
  '/purchase-order': typeof PurchaseOrderRoute
  '/receiving': typeof ReceivingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/submit-quotation': typeof SubmitQuotationRoute
  '/supplier-dashboard': typeof SupplierDashboardRoute
  '/vehicle-queue': typeof VehicleQueueRoute
  '/vehicle-verification': typeof VehicleVerificationRoute
  '/procurement/asns': typeof ProcurementAsnsRoute
  '/procurement/new-po': typeof ProcurementNewPoRoute
  '/procurement/new-rfq': typeof ProcurementNewRfqRoute
  '/procurement/po-detail': typeof ProcurementPoDetailRoute
  '/procurement/purchase-orders': typeof ProcurementPurchaseOrdersRoute
  '/procurement/quotations': typeof ProcurementQuotationsRoute
  '/procurement/rfqs': typeof ProcurementRfqsRoute
  '/supplier/$supplierId': typeof SupplierSupplierIdRoute
  '/supplier/asns/new': typeof SupplierAsnsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-arrival': typeof AcceptArrivalRoute
  '/arrival-success': typeof ArrivalSuccessRoute
  '/dashboard': typeof DashboardRoute
  '/dock-assignment': typeof DockAssignmentRoute
  '/driver-verification': typeof DriverVerificationRoute
  '/finance-approval': typeof FinanceApprovalRoute
  '/finance-dashboard': typeof FinanceDashboardRoute
  '/gate-entry': typeof GateEntryRoute
  '/grn': typeof GrnRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/master-data': typeof MasterDataRoute
  '/new-supplier': typeof NewSupplierRoute
  '/notifications': typeof NotificationsRoute
  '/procurement-dashboard': typeof ProcurementDashboardRoute
  '/purchase-order': typeof PurchaseOrderRoute
  '/receiving': typeof ReceivingRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/submit-quotation': typeof SubmitQuotationRoute
  '/supplier-dashboard': typeof SupplierDashboardRoute
  '/vehicle-queue': typeof VehicleQueueRoute
  '/vehicle-verification': typeof VehicleVerificationRoute
  '/procurement/asns': typeof ProcurementAsnsRoute
  '/procurement/new-po': typeof ProcurementNewPoRoute
  '/procurement/new-rfq': typeof ProcurementNewRfqRoute
  '/procurement/po-detail': typeof ProcurementPoDetailRoute
  '/procurement/purchase-orders': typeof ProcurementPurchaseOrdersRoute
  '/procurement/quotations': typeof ProcurementQuotationsRoute
  '/procurement/rfqs': typeof ProcurementRfqsRoute
  '/supplier/$supplierId': typeof SupplierSupplierIdRoute
  '/supplier/asns/new': typeof SupplierAsnsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-arrival'
    | '/arrival-success'
    | '/dashboard'
    | '/dock-assignment'
    | '/driver-verification'
    | '/finance-approval'
    | '/finance-dashboard'
    | '/gate-entry'
    | '/grn'
    | '/inventory'
    | '/login'
    | '/master-data'
    | '/new-supplier'
    | '/notifications'
    | '/procurement-dashboard'
    | '/purchase-order'
    | '/receiving'
    | '/reports'
    | '/settings'
    | '/submit-quotation'
    | '/supplier-dashboard'
    | '/vehicle-queue'
    | '/vehicle-verification'
    | '/procurement/asns'
    | '/procurement/new-po'
    | '/procurement/new-rfq'
    | '/procurement/po-detail'
    | '/procurement/purchase-orders'
    | '/procurement/quotations'
    | '/procurement/rfqs'
    | '/supplier/$supplierId'
    | '/supplier/asns/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-arrival'
    | '/arrival-success'
    | '/dashboard'
    | '/dock-assignment'
    | '/driver-verification'
    | '/finance-approval'
    | '/finance-dashboard'
    | '/gate-entry'
    | '/grn'
    | '/inventory'
    | '/login'
    | '/master-data'
    | '/new-supplier'
    | '/notifications'
    | '/procurement-dashboard'
    | '/purchase-order'
    | '/receiving'
    | '/reports'
    | '/settings'
    | '/submit-quotation'
    | '/supplier-dashboard'
    | '/vehicle-queue'
    | '/vehicle-verification'
    | '/procurement/asns'
    | '/procurement/new-po'
    | '/procurement/new-rfq'
    | '/procurement/po-detail'
    | '/procurement/purchase-orders'
    | '/procurement/quotations'
    | '/procurement/rfqs'
    | '/supplier/$supplierId'
    | '/supplier/asns/new'
  id:
    | '__root__'
    | '/'
    | '/accept-arrival'
    | '/arrival-success'
    | '/dashboard'
    | '/dock-assignment'
    | '/driver-verification'
    | '/finance-approval'
    | '/finance-dashboard'
    | '/gate-entry'
    | '/grn'
    | '/inventory'
    | '/login'
    | '/master-data'
    | '/new-supplier'
    | '/notifications'
    | '/procurement-dashboard'
    | '/purchase-order'
    | '/receiving'
    | '/reports'
    | '/settings'
    | '/submit-quotation'
    | '/supplier-dashboard'
    | '/vehicle-queue'
    | '/vehicle-verification'
    | '/procurement/asns'
    | '/procurement/new-po'
    | '/procurement/new-rfq'
    | '/procurement/po-detail'
    | '/procurement/purchase-orders'
    | '/procurement/quotations'
    | '/procurement/rfqs'
    | '/supplier/$supplierId'
    | '/supplier/asns/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptArrivalRoute: typeof AcceptArrivalRoute
  ArrivalSuccessRoute: typeof ArrivalSuccessRoute
  DashboardRoute: typeof DashboardRoute
  DockAssignmentRoute: typeof DockAssignmentRoute
  DriverVerificationRoute: typeof DriverVerificationRoute
  FinanceApprovalRoute: typeof FinanceApprovalRoute
  FinanceDashboardRoute: typeof FinanceDashboardRoute
  GateEntryRoute: typeof GateEntryRoute
  GrnRoute: typeof GrnRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  MasterDataRoute: typeof MasterDataRoute
  NewSupplierRoute: typeof NewSupplierRoute
  NotificationsRoute: typeof NotificationsRoute
  ProcurementDashboardRoute: typeof ProcurementDashboardRoute
  PurchaseOrderRoute: typeof PurchaseOrderRoute
  ReceivingRoute: typeof ReceivingRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SubmitQuotationRoute: typeof SubmitQuotationRoute
  SupplierDashboardRoute: typeof SupplierDashboardRoute
  VehicleQueueRoute: typeof VehicleQueueRoute
  VehicleVerificationRoute: typeof VehicleVerificationRoute
  ProcurementAsnsRoute: typeof ProcurementAsnsRoute
  ProcurementNewPoRoute: typeof ProcurementNewPoRoute
  ProcurementNewRfqRoute: typeof ProcurementNewRfqRoute
  ProcurementPoDetailRoute: typeof ProcurementPoDetailRoute
  ProcurementPurchaseOrdersRoute: typeof ProcurementPurchaseOrdersRoute
  ProcurementQuotationsRoute: typeof ProcurementQuotationsRoute
  ProcurementRfqsRoute: typeof ProcurementRfqsRoute
  SupplierSupplierIdRoute: typeof SupplierSupplierIdRoute
  SupplierAsnsNewRoute: typeof SupplierAsnsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-arrival': {
      id: '/accept-arrival'
      path: '/accept-arrival'
      fullPath: '/accept-arrival'
      preLoaderRoute: typeof AcceptArrivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrival-success': {
      id: '/arrival-success'
      path: '/arrival-success'
      fullPath: '/arrival-success'
      preLoaderRoute: typeof ArrivalSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dock-assignment': {
      id: '/dock-assignment'
      path: '/dock-assignment'
      fullPath: '/dock-assignment'
      preLoaderRoute: typeof DockAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-verification': {
      id: '/driver-verification'
      path: '/driver-verification'
      fullPath: '/driver-verification'
      preLoaderRoute: typeof DriverVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-approval': {
      id: '/finance-approval'
      path: '/finance-approval'
      fullPath: '/finance-approval'
      preLoaderRoute: typeof FinanceApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-dashboard': {
      id: '/finance-dashboard'
      path: '/finance-dashboard'
      fullPath: '/finance-dashboard'
      preLoaderRoute: typeof FinanceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate-entry': {
      id: '/gate-entry'
      path: '/gate-entry'
      fullPath: '/gate-entry'
      preLoaderRoute: typeof GateEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grn': {
      id: '/grn'
      path: '/grn'
      fullPath: '/grn'
      preLoaderRoute: typeof GrnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-data': {
      id: '/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof MasterDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-supplier': {
      id: '/new-supplier'
      path: '/new-supplier'
      fullPath: '/new-supplier'
      preLoaderRoute: typeof NewSupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement-dashboard': {
      id: '/procurement-dashboard'
      path: '/procurement-dashboard'
      fullPath: '/procurement-dashboard'
      preLoaderRoute: typeof ProcurementDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-order': {
      id: '/purchase-order'
      path: '/purchase-order'
      fullPath: '/purchase-order'
      preLoaderRoute: typeof PurchaseOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receiving': {
      id: '/receiving'
      path: '/receiving'
      fullPath: '/receiving'
      preLoaderRoute: typeof ReceivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-quotation': {
      id: '/submit-quotation'
      path: '/submit-quotation'
      fullPath: '/submit-quotation'
      preLoaderRoute: typeof SubmitQuotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-dashboard': {
      id: '/supplier-dashboard'
      path: '/supplier-dashboard'
      fullPath: '/supplier-dashboard'
      preLoaderRoute: typeof SupplierDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-queue': {
      id: '/vehicle-queue'
      path: '/vehicle-queue'
      fullPath: '/vehicle-queue'
      preLoaderRoute: typeof VehicleQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-verification': {
      id: '/vehicle-verification'
      path: '/vehicle-verification'
      fullPath: '/vehicle-verification'
      preLoaderRoute: typeof VehicleVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/asns': {
      id: '/procurement/asns'
      path: '/procurement/asns'
      fullPath: '/procurement/asns'
      preLoaderRoute: typeof ProcurementAsnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/new-po': {
      id: '/procurement/new-po'
      path: '/procurement/new-po'
      fullPath: '/procurement/new-po'
      preLoaderRoute: typeof ProcurementNewPoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/new-rfq': {
      id: '/procurement/new-rfq'
      path: '/procurement/new-rfq'
      fullPath: '/procurement/new-rfq'
      preLoaderRoute: typeof ProcurementNewRfqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/po-detail': {
      id: '/procurement/po-detail'
      path: '/procurement/po-detail'
      fullPath: '/procurement/po-detail'
      preLoaderRoute: typeof ProcurementPoDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/purchase-orders': {
      id: '/procurement/purchase-orders'
      path: '/procurement/purchase-orders'
      fullPath: '/procurement/purchase-orders'
      preLoaderRoute: typeof ProcurementPurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/quotations': {
      id: '/procurement/quotations'
      path: '/procurement/quotations'
      fullPath: '/procurement/quotations'
      preLoaderRoute: typeof ProcurementQuotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement/rfqs': {
      id: '/procurement/rfqs'
      path: '/procurement/rfqs'
      fullPath: '/procurement/rfqs'
      preLoaderRoute: typeof ProcurementRfqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/$supplierId': {
      id: '/supplier/$supplierId'
      path: '/supplier/$supplierId'
      fullPath: '/supplier/$supplierId'
      preLoaderRoute: typeof SupplierSupplierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/asns/new': {
      id: '/supplier/asns/new'
      path: '/supplier/asns/new'
      fullPath: '/supplier/asns/new'
      preLoaderRoute: typeof SupplierAsnsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptArrivalRoute: AcceptArrivalRoute,
  ArrivalSuccessRoute: ArrivalSuccessRoute,
  DashboardRoute: DashboardRoute,
  DockAssignmentRoute: DockAssignmentRoute,
  DriverVerificationRoute: DriverVerificationRoute,
  FinanceApprovalRoute: FinanceApprovalRoute,
  FinanceDashboardRoute: FinanceDashboardRoute,
  GateEntryRoute: GateEntryRoute,
  GrnRoute: GrnRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  MasterDataRoute: MasterDataRoute,
  NewSupplierRoute: NewSupplierRoute,
  NotificationsRoute: NotificationsRoute,
  ProcurementDashboardRoute: ProcurementDashboardRoute,
  PurchaseOrderRoute: PurchaseOrderRoute,
  ReceivingRoute: ReceivingRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SubmitQuotationRoute: SubmitQuotationRoute,
  SupplierDashboardRoute: SupplierDashboardRoute,
  VehicleQueueRoute: VehicleQueueRoute,
  VehicleVerificationRoute: VehicleVerificationRoute,
  ProcurementAsnsRoute: ProcurementAsnsRoute,
  ProcurementNewPoRoute: ProcurementNewPoRoute,
  ProcurementNewRfqRoute: ProcurementNewRfqRoute,
  ProcurementPoDetailRoute: ProcurementPoDetailRoute,
  ProcurementPurchaseOrdersRoute: ProcurementPurchaseOrdersRoute,
  ProcurementQuotationsRoute: ProcurementQuotationsRoute,
  ProcurementRfqsRoute: ProcurementRfqsRoute,
  SupplierSupplierIdRoute: SupplierSupplierIdRoute,
  SupplierAsnsNewRoute: SupplierAsnsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
